apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kanban

resources:
  - namespace.yaml
  - redis.yaml
  - task-service.yaml
  - stats-service.yaml
  - frontend.yaml

# CI cap nhat newTag theo commit SHA; ArgoCD thay doi nay va tu sync
images:
  - name: ghcr.io/nghiant05/kanban-frontend
    newTag: latest
  - name: ghcr.io/nghiant05/kanban-task-service
    newTag: latest
  - name: ghcr.io/nghiant05/kanban-stats-service
    newTag: latest
