apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kanban

resources:
  - namespace.yaml
  - redis.yaml
  - task-service.yaml
  - stats-service.yaml
  - frontend.yaml

# CI cap nhat newTag theo commit SHA; ArgoCD thay doi nay va tu sync
images:
  - name: ghcr.io/nghiant05/kanban-frontend
    newTag: 7b8e71f21a2c8b28bf39b4cde6c331615dca8ad3
  - name: ghcr.io/nghiant05/kanban-task-service
    newTag: 7b8e71f21a2c8b28bf39b4cde6c331615dca8ad3
  - name: ghcr.io/nghiant05/kanban-stats-service
    newTag: 7b8e71f21a2c8b28bf39b4cde6c331615dca8ad3
